### PR TITLE
Done files

### LINKED ISSUE #27: [FEATURE] - Delete page
Currenty Set-DokuPageData has         [ValidateNotNullOrEmpty()] on the $RawWikiText parameter which means you can't set the page to ""

Could we either implement an explicit "Delete-DokuPageData" method which effectively called Set-DokuPageData with "" on it, or allow "" on the Set method?

### PR DESCRIPTION
**Pull request by asmith3006**
Created new Remove-DokuPageData function.

Really just a copy of the Set-DokuPageData function but sets it to ""

This is the first time I've contributed to a project so please feel free to give me feedback. I was unable to test the tests though so if you can give me pointers on that too I'd appreciate it.  The error I get is ``Install-Module -Name Pester ``

### CODE REVIEW

**Comment by AndyDLP** [comment]
Hey,

You can run the tests locally but tbh I'm having trouble with Pester 5.0. I've ended up forcing use of Pester 4.0 with the build as that's what I originally did it with. To run the tests, just change directory to the repository root and then run the .\build.ps1 script. NOTE: I had to uninstall fully pester 5 (I'm not using any of the functionality anyway atm)

I've re-ran the tests in AV, so you should now be able to see the test results by clicking on the details link below (you can ignore the help tests for now, as it's testing existence of the help before it is generated).

A couple of things I thought:
- You may also want to update the markdown help to remove the output type, add input type & put your name on it if you want.
- I think that "Remove-DokuPage" makes more sense as a function name, given the end result but it's up to you.

Cheers,
Andy

**Comment by AndyDLP** [comment]
Hey, it looks like you committed the generated pester test results .xml file and left the passthru in (unless I'm looking at the wrong commit... 5951590).

Andy

**Comment by asmith3006** [comment]
> 
> 
> Hey, it looks like you committed the generated pester test results .xml file and left the passthru in (unless I'm looking at the wrong commit... [5951590](https://github.com/AndyDLP/PSDokuWiki/commit/5951590186ab815adf41ac90083ad9e6f256d003)).
> 
> Andy

Sorry, I don't know how that happened. It's showing as committed (without the PassThru flag) on my branch, I've done something wrong. Like I said, I'm new to this.

**Comment by asmith3006** [comment]
I'm not able to run the local .\build.ps1 on my computer, I get the following error:

``` powershell
Error: 28/07/2020 14:49:39:
At C:\Work\PSDokuWiki\psake.ps1:133 char:5 +     $CodeCoverage.Statement.Coverage = [math]::Round($CodeCoverage.St ... +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Attempted to divide by zero. --> Attempted to divide by zero.
```
Any suggestions? I'd really like to run the tests locally before uploading and making another mistake.

**Comment by AndyDLP** [comment]
I was getting that same error with Pester 5 so I've made some changes to the build script so it should force usage of Pester 4.10.1 even if 5.0+ is installed, let me know if you have any trouble with it.

**Pull request merged**
